#Server
server:
  port: 8080

spring:
  #Database
  datasource:
    url: jdbc:postgresql://localhost:5432/notificator
    username: postgres
    password: postgres
    jpa:
        hibernate:
            ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: mail01notificator@gmail.com
    password: //*****************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #RabbitMQ
  rabbitmq:
    queue: email
    addresses: amqps://********************************************.cloudamqp.com

