#Server
server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #RabbitMQ
  rabbitmq:
    queue: email
    addresses: ${RABBITMQ_CONNECTION}
