on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: vitortenorio/descomplicando
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: |
            EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} 
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            RABBITMQ_CONNECTION=${{ secrets.RABBITMQ_CONNECTION }}
